# Generated by Django 6.0.3 on 2026-05-09 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_enrollment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entrollment',
        ),
    ]
